version: 2

updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '06:00'
          timezone: 'America/Toronto'
      open-pull-requests-limit: 10
      rebase-strategy: 'auto'

      groups:
          production-deps:
              dependency-type: 'production'
              update-types: ['minor', 'patch']
          dev-deps:
              dependency-type: 'development'
              update-types: ['minor', 'patch']

      commit-message:
          prefix: '⬆️'
          include: scope

      labels:
          - 'dependencies'
          - 'npm'
